import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Users,GraduationCap,Building2,CreditCard,Plus,Search,Pencil,Trash2,X,Save,ShieldCheck} from 'lucide-react';
import './styles.css';
const API=(import.meta.env.VITE_API_URL||'http://localhost:8080').replace(/\/$/,'');
async function request(path,options={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||`Request failed: ${r.status}`);return data}
const emptyStudent={id:'',name:'',email:'',program:'',department:'',nfcUid:'',status:'ACTIVE'};
const emptyFaculty={id:'',name:'',email:'',designation:'Assistant Professor',departmentCode:'',officeRoom:'',nfcUid:'',status:'ACTIVE'};
function Modal({title,onClose,children}){return <div className="overlay"><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon" onClick={onClose}><X/></button></div>{children}</div></div>}
function NfcField({value,onChange,onCaptured}){
 const normalize=v=>String(v||'').replace(/[^a-fA-F0-9]/g,'').toUpperCase();
 return <label>NFC Card UID<div className="nfc-row"><input autoFocus required value={value||''} onChange={e=>onChange(normalize(e.target.value))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();const uid=normalize(e.currentTarget.value);onChange(uid);if(uid)onCaptured(uid)}}} placeholder="Tap card on USB NFC reader"/><button type="button" className="reader-button" onClick={e=>{const input=e.currentTarget.previousElementSibling;input.focus();input.select()}}><CreditCard/>Ready to Scan</button></div><small className="reader-help">Connect a keyboard-emulation NFC reader, click Ready to Scan, then tap the card. The UID is captured when the reader sends Enter.</small></label>
}
function App(){
 const [tab,setTab]=useState('students'),[students,setStudents]=useState([]),[faculties,setFaculties]=useState([]),[departments,setDepartments]=useState([]),[stats,setStats]=useState({}),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[studentForm,setStudentForm]=useState(null),[facultyForm,setFacultyForm]=useState(null),[departmentForm,setDepartmentForm]=useState(null),[editing,setEditing]=useState(false);
 const load=async()=>{try{const [s,f,d,st]=await Promise.all([request('/api/students'),request('/api/faculties'),request('/api/departments'),request('/api/admin/stats')]);setStudents(s);setFaculties(f);setDepartments(d);setStats(st);setError('')}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const filteredStudents=useMemo(()=>students.filter(s=>`${s.id} ${s.name} ${s.email||''} ${s.department} ${s.nfcUid}`.toLowerCase().includes(query.toLowerCase())),[students,query]);
 const filteredFaculties=useMemo(()=>faculties.filter(f=>`${f.id} ${f.name} ${f.email||''} ${f.designation} ${f.departmentCode}`.toLowerCase().includes(query.toLowerCase())),[faculties,query]);
 const flash=m=>{setNotice(m);setTimeout(()=>setNotice(''),2500)};
 const saveStudent=async e=>{e.preventDefault();try{await request(`/api/students${editing?'/'+encodeURIComponent(studentForm.id):''}`,{method:editing?'PUT':'POST',body:JSON.stringify(studentForm)});setStudentForm(null);flash(editing?'Student updated.':'Student and NFC card registered.');await load()}catch(e){setError(e.message)}};
 const saveFaculty=async e=>{e.preventDefault();try{await request(`/api/faculties${editing?'/'+encodeURIComponent(facultyForm.id):''}`,{method:editing?'PUT':'POST',body:JSON.stringify(facultyForm)});setFacultyForm(null);flash(editing?'Faculty record updated.':'Faculty/professor registered.');await load()}catch(e){setError(e.message)}};
 const saveDepartment=async e=>{e.preventDefault();try{await request('/api/departments',{method:'POST',body:JSON.stringify(departmentForm)});setDepartmentForm(null);flash('Department registered.');await load()}catch(e){setError(e.message)}};
 const del=async(type,id)=>{if(!confirm(`Delete this ${type} record?`))return;try{await request(`/api/${type}/${encodeURIComponent(id)}`,{method:'DELETE'});flash('Record deleted.');await load()}catch(e){setError(e.message)}};
 return <div className="shell"><aside><div className="brand"><ShieldCheck/><div><strong>NSU Architecture Admin</strong><small>Identity & NFC Registry</small></div></div><nav><button className={tab==='students'?'active':''} onClick={()=>setTab('students')}><GraduationCap/>Students</button><button className={tab==='faculties'?'active':''} onClick={()=>setTab('faculties')}><Users/>Faculty & Professors</button><button className={tab==='departments'?'active':''} onClick={()=>setTab('departments')}><Building2/>Departments</button></nav><div className="server">API<br/><span>{API}</span></div></aside><main><header><div><h1>Administration Dashboard</h1><p>Register university identities and NFC cards</p></div></header>{error&&<div className="alert error" onClick={()=>setError('')}>{error}</div>}{notice&&<div className="alert success">{notice}</div>}<section className="stats"><article><GraduationCap/><div><span>Students</span><strong>{stats.students||0}</strong></div></article><article><CreditCard/><div><span>NFC Cards</span><strong>{stats.registeredCards||0}</strong></div></article><article><Users/><div><span>Faculty</span><strong>{stats.faculties||0}</strong></div></article><article><Building2/><div><span>Departments</span><strong>{stats.departments||0}</strong></div></article></section><section className="panel"><div className="toolbar"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${tab}...`}/></div>{tab==='students'&&<button className="primary" onClick={()=>{setEditing(false);setStudentForm({...emptyStudent,department:departments[0]?.code||''})}}><Plus/>Register Student</button>}{tab==='faculties'&&<button className="primary" onClick={()=>{setEditing(false);setFacultyForm({...emptyFaculty,departmentCode:departments[0]?.code||''})}}><Plus/>Register Faculty</button>}{tab==='departments'&&<button className="primary" onClick={()=>setDepartmentForm({code:'',name:''})}><Plus/>Add Department</button>}</div>
 {tab==='students'&&<div className="table-wrap"><table><thead><tr><th>Student</th><th>Department</th><th>NFC UID</th><th>Status</th><th></th></tr></thead><tbody>{filteredStudents.map(s=><tr key={s.id}><td><b>{s.name}</b><small>{s.id} · {s.email||'No email'}</small></td><td>{s.department}<small>{s.program||'Program not set'}</small></td><td><code>{s.nfcUid}</code></td><td><span className={`badge ${s.status==='ACTIVE'?'green':'gray'}`}>{s.status}</span></td><td className="actions"><button onClick={()=>{setEditing(true);setStudentForm({...s})}}><Pencil/></button><button onClick={()=>del('students',s.id)}><Trash2/></button></td></tr>)}</tbody></table></div>}
 {tab==='faculties'&&<div className="table-wrap"><table><thead><tr><th>Faculty / Professor</th><th>Designation</th><th>Department</th><th>Office</th><th>Status</th><th></th></tr></thead><tbody>{filteredFaculties.map(f=><tr key={f.id}><td><b>{f.name}</b><small>{f.id} · {f.email||'No email'}</small></td><td>{f.designation}</td><td>{f.departmentCode}</td><td>{f.officeRoom||'—'}</td><td><span className={`badge ${f.status!=='INACTIVE'?'green':'gray'}`}>{f.status||'ACTIVE'}</span></td><td className="actions"><button onClick={()=>{setEditing(true);setFacultyForm({...f})}}><Pencil/></button><button onClick={()=>del('faculties',f.id)}><Trash2/></button></td></tr>)}</tbody></table></div>}
 {tab==='departments'&&<div className="cards">{departments.filter(d=>`${d.code} ${d.name}`.toLowerCase().includes(query.toLowerCase())).map(d=><article className="dept" key={d.code}><div>{d.code}</div><h3>{d.name}</h3><p>{students.filter(s=>s.department===d.code).length} students · {faculties.filter(f=>f.departmentCode===d.code).length} faculty</p></article>)}</div>}</section></main>
 {studentForm&&<Modal title={editing?'Edit Student':'Register Student & NFC Card'} onClose={()=>setStudentForm(null)}><form onSubmit={saveStudent} className="form"><label>Student ID<input required disabled={editing} value={studentForm.id} onChange={e=>setStudentForm({...studentForm,id:e.target.value})}/></label><label>Full Name<input required value={studentForm.name} onChange={e=>setStudentForm({...studentForm,name:e.target.value})}/></label><label>Email<input type="email" value={studentForm.email||''} onChange={e=>setStudentForm({...studentForm,email:e.target.value})}/></label><label>Program<input value={studentForm.program||''} onChange={e=>setStudentForm({...studentForm,program:e.target.value})}/></label><label>Department<select value={studentForm.department} onChange={e=>setStudentForm({...studentForm,department:e.target.value})}>{departments.map(d=><option key={d.code} value={d.code}>{d.code} — {d.name}</option>)}</select></label><NfcField value={studentForm.nfcUid} onChange={nfcUid=>setStudentForm({...studentForm,nfcUid})} onCaptured={uid=>flash(`Student card captured: ${uid}`)}/><label>Status<select value={studentForm.status} onChange={e=>setStudentForm({...studentForm,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option><option>BLOCKED</option></select></label><button className="primary submit"><Save/>Save Student</button></form></Modal>}
 {facultyForm&&<Modal title={editing?'Edit Faculty / Professor':'Register Faculty / Professor'} onClose={()=>setFacultyForm(null)}><form onSubmit={saveFaculty} className="form"><label>Employee ID<input required disabled={editing} value={facultyForm.id} onChange={e=>setFacultyForm({...facultyForm,id:e.target.value})}/></label><label>Full Name<input required value={facultyForm.name} onChange={e=>setFacultyForm({...facultyForm,name:e.target.value})}/></label><label>Email<input type="email" value={facultyForm.email||''} onChange={e=>setFacultyForm({...facultyForm,email:e.target.value})}/></label><label>Designation<select value={facultyForm.designation} onChange={e=>setFacultyForm({...facultyForm,designation:e.target.value})}><option>Lecturer</option><option>Senior Lecturer</option><option>Assistant Professor</option><option>Associate Professor</option><option>Professor</option></select></label><label>Department<select value={facultyForm.departmentCode} onChange={e=>setFacultyForm({...facultyForm,departmentCode:e.target.value})}>{departments.map(d=><option key={d.code} value={d.code}>{d.code} — {d.name}</option>)}</select></label><label>Office Room<input value={facultyForm.officeRoom||''} onChange={e=>setFacultyForm({...facultyForm,officeRoom:e.target.value})}/></label><NfcField value={facultyForm.nfcUid} onChange={nfcUid=>setFacultyForm({...facultyForm,nfcUid})} onCaptured={uid=>flash(`Staff card captured: ${uid}`)}/><label>Status<select value={facultyForm.status||'ACTIVE'} onChange={e=>setFacultyForm({...facultyForm,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option><option>ON_LEAVE</option></select></label><button className="primary submit"><Save/>Save Faculty</button></form></Modal>}
 {departmentForm&&<Modal title="Add Department" onClose={()=>setDepartmentForm(null)}><form onSubmit={saveDepartment} className="form"><label>Department Code<input required value={departmentForm.code} onChange={e=>setDepartmentForm({...departmentForm,code:e.target.value.toUpperCase()})}/></label><label>Department Name<input required value={departmentForm.name} onChange={e=>setDepartmentForm({...departmentForm,name:e.target.value})}/></label><button className="primary submit"><Save/>Save Department</button></form></Modal>}
 </div>}
createRoot(document.getElementById('root')).render(<App/>);
